### ISSUE TITLE
Inconsistency in documentation

### ISSUE THREAD

**Issue by cpitclaudel** [Malabarba/Nameless#1]
For `nameless-aliases`:

```
Alist from namespaces to aliases.
...
```

For `nameless-global-aliases`:

```
Alist from aliases to namespaces.
...
```

Also, in the docs of nameless-aliases, "Samse syntax" should read "Same syntax".

Thanks for this package, it looks exciting!

**Comment by Malabarba** [comment]
Thanks for catching that! Fixed now.
