### ISSUE TITLE
`nameless-current-name` cannot be set locally

### ISSUE THREAD

**Issue by cpitclaudel** [Malabarba/Nameless#12]
Hi Artur,

The documentation says `In these situations, simply set nameless-current-name as file-local variable.`, but that doesn't seem to work for me. The code of `nameless-mode` doesn't register a `hack-local-variables` hook, and sets `current-name` to `nil` when disabled.

Am I doing something wrong?
Thanks!

**Comment by Malabarba** [comment]
What do you mean by "when disabled"? 

Also, what version of nameless do you have?

**Comment by cpitclaudel** [comment]
> What do you mean by "when disabled"? 

When the mode is turned off. I was trying to toggle it off and back on to see if it would pick up the change, but that didn't do because the custom value of `current-name` was cleared.

> Also, what version of nameless do you have? 

`20151014.439`; it seems to be the latest on MELPA.

**Comment by Malabarba** [comment]
Oh wait, are you sure you followed the readme instructions?

```
(add-hook 'emacs-lisp-mode-hook #'nameless-mode-from-hook)
```

**Comment by cpitclaudel** [comment]
No, definitely not :/ Looks like I installed this mode before they existed :)

**Comment by cpitclaudel** [comment]
Works great :) Is there a reason for doing that instead of using `hack-local-variables-hook`?

**Comment by Malabarba** [comment]
None. I just didn't know about it. :-)
I'll look into it later.

**Comment by cpitclaudel** [comment]
:)

**Comment by cpitclaudel** [comment]
I think the issue still exists, actually :/ Disabling then re-enabling clears the file-locally set `nameless-current-name` variable.
