### ISSUE TITLE
Please tag latest commit

### ISSUE THREAD

**Issue by DamienCassou** [Malabarba/Nameless#13]
Could you please tag the current commit so that the package appears on melpa stable? You can do it through github in the "releases" tab or through `git tag`. Thanks

**Comment by Malabarba** [comment]
This package is on Gnu Elpa, so you should always be able to get stable releases from there. Is there any reason that doesn't work for you?

**Comment by DamienCassou** [comment]
Artur Malabarba notifications@github.com writes:

> This package is on Gnu Elpa, so you should always be able to get
> stable releases from there. Is there any reason that doesn't work for
> you?

you are right, thank you. I just didn't check.

## 

Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill
