### ISSUE TITLE
private-prefix seems broken

### ISSUE THREAD

**Issue by cpitclaudel** [Malabarba/Nameless#14]
Here's a repro:

``` elisp
(defun test-public ()
  "Call `test--private'.")
(defun test--private ()
  "Call `test-public'")

;; Local Variables:
;; nameless-current-name: "test"
;; nameless-private-prefix: t
;; End:
```

This renders to the following for me:

![screenshot from 2016-07-03 13 40 45](https://cloud.githubusercontent.com/assets/8181630/16546786/c3176cd0-4123-11e6-9b5a-b0e1c3032936.png)

The `::` works fine in docstrings, but not in plain code.

**Comment by Malabarba** [comment]
I think it's the same display bug as in #15. Note that it works if you set `nameless-affect-indentation-and-filling` to nil (which uses a different display method)

**Comment by cpitclaudel** [comment]
Neat; you'll get to close two bugs at once :) Or I can close it now.

**Comment by Malabarba** [comment]
I'll just close it as duplicate so we don't forget later. :-)
