### ISSUE TITLE
Using a prefix argument with _ inserts 4 copies of it

### ISSUE THREAD

**Issue by cpitclaudel** [Malabarba/Nameless#3]
I often need underscores in `pcase` or `pcase-let` bindings. At the moment <kbd> _ </kbd> inserts the package name, and <kbd>C-u _</kbd> inserts "____". Could <kbd>C-u _</kbd> maybe be made to only insert one underscore?

**Comment by Malabarba** [comment]
Oh, I forgot about pcase. I'll add specific support for it in that command so this doesn't happen.

In any case, for now you can insert one underscore with `C-q _` or `C-1 _`.

**Comment by Malabarba** [comment]
Also, I'm still unsure about that `_` binding, so you could experiment with changing it if you use that feature.
I wanted to make it easy to type before `-`, but `_` is pretty non-intuitive.

**Comment by cpitclaudel** [comment]
The <kbd>C-q</kbd> tip is smart, thanks!
Could the trick be to recognize the sequence <kbd>_-</kbd> instead of <kbd>_</kbd> alone?

**Comment by Malabarba** [comment]
No, because that's not the only use. If you want to type `my-pkg-command` you do `_command`, and if you want to type `my-pkg--internal` you do `_-internal`.

So `prefix` + `-` is a frequent occurrence (which is why I want it to be easy to type) but it's not the only occurrence.

**Comment by cpitclaudel** [comment]
That makes sense (although I could see myself typing `_-` and `_--` for those two cases), thanks!

**Comment by Malabarba** [comment]
By the way, I've removed this keybind by default. It was a little shaky to be turned on by default. Instead, I've set the key C-c C-- to always insert the name.

The command is still there, so you can still defined-key it back to _ if desired.
