### ISSUE TITLE
FYI: Reimplementation using tree-sitter (I didn't know about this package)

### ISSUE THREAD

**Issue by hraban** [Malabarba/Nameless#34]
Hi! Thought I'd reach out as I recently implemented basically this same package, using treesitter. I didn't know about Nameless 🥲 But I learned a lot reading your code, and I thought you might find it interesting to read mine: https://gitlab.com/hraban/hide-package-name-el

All the best

**Comment by hraban** [comment]
Back story: https://github.com/melpa/melpa/pull/8120

**Comment by Malabarba** [comment]
Cool! I'll try to have a look!
Thanks for the ping. :+1:
