### ISSUE TITLE
Comments and Strings?

### ISSUE THREAD

**Issue by dbordak** [Malabarba/Nameless#5]
Is it appropriate to hide namespaces in comments/[doc]strings given how they're often used for usage documentation (e.g. instructing users to add a hook for a given function)? At the very least, you should document this behavior somewhere (I didn't expect it), either textually or in the example screenshots.

**Comment by cpitclaudel** [comment]
This is just a display thing when you look at the source, right? In particular, getting the documentation from `describe-function` doesn't show the abbreviated form, so I wouldn't worry about this at all.

**Comment by dbordak** [comment]
Yeah, it's only when looking at the source, so that aspect doesn't matter. It's still not something I'd expect, though, and the point was that this should be documented.

**Comment by Malabarba** [comment]
I'm pushing a change that explains a little about this on the readme. Further suggestions are welcome.
