### ISSUE TITLE
Multi-file Namespaces

### ISSUE THREAD

**Issue by dbordak** [Malabarba/Nameless#6]
I'm not sure how Nameless determines the current namespace, but so far I gather it's just via defgroup. If that's the case, how should I handle namespaces shared between multiple files?

**Comment by Malabarba** [comment]
It gets the current namespace with the (lm--name) function. Which usually derives the name from the comment at the top of the file. 

If you set the nameless-current-name variable as a file-local-variable, then that variable will be used as the name. 
You can also set it as a dir local variable, so the whole project gets the same name.

**Comment by Malabarba** [comment]
Small correction: the name of the function is
`(lm-get-package-name)` not `lm--name`. (typing on a phone here)

**Comment by dbordak** [comment]
Oh, ok, so then my issue is that the name of the file (or, well, the comment matching the filename) doesn't match the namespace (as would have to happen in any multi-file situation)

**Comment by dbordak** [comment]
I've just tried setting nameless-current-name with a dir local variable. I can confirm it's properly set, but it doesn't appear to have any effect on any of the files in question (the one which already worked continues to do so).

**Comment by Malabarba** [comment]
You're right, that was a bug. Thanks for catching it. It should work properly now.
Note that the way to set up the mode has changed. You're supposed to use `(add-hook 'emacs-lisp-mode-hook #'nameless-mode-from-hook)`.
