### ISSUE TITLE
Undoing expansion

### ISSUE THREAD

**Issue by DamienCassou** [Malabarba/Nameless#8]
When `_` is entered, there is an expansion to get the package name. That's nice. But if I don't want the expansion, I naturally press `<undo>` (`C-_` or `C-/`). Unfortunately, undoing expansion does not bring my `_` back, it removes it as well as the expansion. It would be nice if undoing expansion would let the `_` in place. I think it's natural and this is what some word processors use (for example when they "fix" a typo).

**Comment by Malabarba** [comment]
That would be nice, I'll try to see how to do it.
In any case, I've removed this keybind by default. It was a little shaky to be turned on by default. Instead, I've set the key `C-c C--` to always insert the name.

The command is still there, so you can still defined-key it back to _ if desired.

**Comment by Malabarba** [comment]
Done. Should be up tomorrow.

**Comment by DamienCassou** [comment]
Thank you
